export { default as CalendarioPage } from "./pages/CalendarioPage";
export { default as PacientesPage } from "./pages/PacientesPage";
export { default as InformesPage } from "./pages/InformesPage";
export { default as NotificacionesPage } from "./pages/NotificacionesPage";
export { default as ContactoModal } from "./components/ContactoModal";
export { default as HistorialModal } from "./components/HistorialModal";
export { default as InformeFormModal } from "./components/InformeFormModal";
export { default as PDFViewerModal } from "./components/PDFViewerModal";
export { especialistaApi } from "./especialistaApi";
export { informesApi } from "./informesApi";
